[package]
name = "bldr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
nom = "7.1.1"

[dependencies.tokio]
version = "1.17.0"
features = [ "full" ]